---

- hosts: all
  become: true
  tasks:
    - name: Install apache and php for Debian servers
      tags: apache, debian
      package:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Debian"

    - name: Install apache and php for AlmaLinux servers
      tags: apache,almalinux
      dnf:
        name: 
          - httpd 
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "AlmaLinux"
